### ISSUE TITLE
does this work with 1.9.2

### ISSUE THREAD

**Issue by bootstraponline** [gmailgem/gmail#1]
_From @rkumar on October 25, 2010 15:16_

ruby-1.9.2-head > Gmail.connect("rahulxxx@gmail.com","xxx") do |gmail|
ruby-1.9.2-head >     gmail.inbox.count
ruby-1.9.2-head ?>  end
Net::IMAP::BadResponseError: Unknown command z5if11396491vco.62

and

ruby-1.9.2-head > gmail = Gmail.connect!("rahulxxxx@gmail.com","xxxxx")
NoMethodError: undefined method `data' for "Couldn't login to given GMail account: rahulxxxx@gmail.com

(I am on a macosx snow leopard, using rvm 1.9.2)

_Copied from original issue: nu7hatch/gmail#1_

**Comment by bootstraponline** [comment]
_From @rkumar on October 25, 2010 17:37_

sorry. i had a password incorrect.
